### PR TITLE
Feature/fourier padder

### PR DESCRIPTION
**Pull request by dbadrian**

### CODE REVIEW

**Comment by akosiorek** [comment]
That's exactly what I wanted to avoid with fetch-rebase workflow. See how some commits there are repeated?

**Comment by akosiorek** [comment]
Anyway, I've done it, too. From now on: please do not use the "merge" button here!

**Comment by yezariael** [comment]
Ah shit, was it a consequence of the merge button here? I didnt check that it merged it stupidly.

**Comment by akosiorek** [comment]
It's a consequence of a merge without a prior rebase. Let's do a pull request on github and then I'll rebase and merge, as we discussed at the beginning. Not that it matters that much, might just look cleaner.

**Comment by yezariael** [comment]
I did a rebase before pushing to github, guess I must have messed up
somewhere beforehand in that case.

**Pull request merged**
